language: generic

sudo: required
services: 
  - docker

before_install: 
  - docker build -t jormarcus/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jormarcus/react-test npm test

after_success:
  - docker build -t jormarcus/multi-client ./client
  - docker build -t jormarcus/multi-nginx ./nginx
  - docker build -t jormarcus/multi-server ./server
  - docker build -t jormarcus/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jormarcus/multi-client
  - docker push jormarcus/multi-nginx
  - docker push jormarcus/multi-server
  - docker push jormarcus/multi-worker
